'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

'''

# Add code here

'''
分析：

方法一： 

from collections import Counter
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        a=list(s)
        b=list(t)
        for aa in a:
            if aa in b:
                b.remove(aa)
        return b[0]

方法二：

def findTheDifference(self, s: str, t: str) -> str:
        for i in t:
            if t.count(i) != s.count(i):
                return i

'''